### ISSUE TITLE
krx.read 에서 시세에 대하여

### ISSUE THREAD

**Issue by min7014** [CoreDotToday/CoreDotFinance#136]
krx.read를 통해 가격 정보를 받을 수 있습니다.
여기서 두 가지를 분리했으면 합니다.
즉, 장이 끝난 날과 장중으로 
실제로 장중에 데이터를 받아보면 close 의 가격이 변합니다. 
어쩜 당연한데, 실제로는 장이 끝났기 때문에 close가격은 없는 것이 맞을 것 같기도 합니다.
나름 날짜 정보의 조작(?)으로 이걸 해결 하는데
근본적으로 krx.read는 장이 끝난 정보만 제공하는 것이 어떨지...

즉, 오늘 2시에 정보를 요청하였을때, 아직 장이 끝난 것이 아니므로 전날까지의 정보만 가져오게 하는 것이지요.
이것이 논리(?)적으로에 맞다고 보여집니다.

**Comment by DavidKimDY** [comment]
`krx.read()` 의 `end` 인자를 오늘 이전 날짜로 설정하여 사용하세요.
