### ISSUE TITLE
black을 적용해서 push 하기

### ISSUE THREAD

**Issue by DavidKimDY** [CoreDotToday/CoreDotFinance#33]
black formatter 를 적용해서 CoreDotFinance repo에 PR 하려고 합니다.
모두가 black을 쓰는 것에 동의한다고 판단하였는데 아니라면 이야기해주세요~!

**Comment by jourmooney** [comment]
저장 시 자동 Formatting 기능이나 Git Hook 기능을 사용하면 적용에는 그리 큰 시간이 들지 않을 듯 합니다.

PR 전에 대엽님께서 작성하신 코드에 Black을 적용해보시고 괜찮으신 지 확인하시고 알려주세요!
