### ISSUE TITLE
coin 프로젝트 추가

### ISSUE THREAD

**Issue by koorukuroo** [CoreDotToday/CoreDotFinance#8]
- [x] coin 폴더 추가
- [x] coin/binance 폴더 추가
- [x] 하부 폴더에 README.rst 추가
- [ ] setup.py 에 coin.binance 연동 추가

**Comment by gukmoon** [comment]
폴더 이름은 coin 대신 crypto로 만들었어요. readme 상 import는 as coin으로 하게 만들었지만...

**Comment by gukmoon** [comment]
`setup.py 에 coin.binance 연동 추가`는 setup.py에 PACKAGES에 추가하라는 말씀일까요?

아래와 같은 방법도 있긴 하더라구요. (출처 : https://rampart81.github.io/post/python_package_publish/)
`from setuptools import setup, find_packages`
`packages = find_packages(exclude = ['docs', 'tests*']),`

**Comment by koorukuroo** [comment]
> 폴더 이름은 coin 대신 crypto로 만들었어요. readme 상 import는 as coin으로 하게 만들었지만...

오 crypto 가 더 나은 의미일 수 있겠네요!

**Comment by jourmooney** [comment]
#27 setup.py 에 coin.crypto 연동 추가
